### PR TITLE
PIE CHART: Represents time spent per activity for all projects.

### PR DESCRIPTION
**Pull request by iCHAIT**
@Kennric Should  be ready for review

### CODE REVIEW

**Comment by MaraJade** [comment]
The dropdown doesn't show any options, and upon clicking the submit button I get this:

`NoMethodError - undefined method`each' for nil:NilClass:
    app.rb:91:in `block (2 levels) in <main>'
    app.rb:83:in`each'
    app.rb:83:in `block in <main>'
    /home/goossenm/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in`call'
    /home/goossenm/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `block in compile!'
    /home/goossenm/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in`[]'
    /home/goossenm/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (3 levels) in route!'
    /home/goossenm/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:994:in`route_eval'
    /home/goossenm/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (2 levels) in route!'
    /home/goossenm/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:1015:in`block in process_route'
    /home/goossenm/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `catch'
    /home/goossenm/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in`process_route'
    /home/goossenm/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:973:in `block in route!'
    /home/goossenm/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in`each'
    /home/goossenm/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `route!'
    /home/goossenm/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:1085:in`block in dispatch!'
    /home/goossenm/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
    /home/goossenm/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in`catch'
    /home/goossenm/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
    /home/goossenm/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:1082:in`dispatch!'
    /home/goossenm/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `block in call!'
    /home/goossenm/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in`block in invoke'
    /home/goossenm/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
    /home/goossenm/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in`invoke'
    /home/goossenm/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `call!'
    /home/goossenm/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:895:in`call'
    /home/goossenm/.rvm/gems/ruby-2.2.2/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
    /home/goossenm/.rvm/gems/ruby-2.2.2/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in`call'
    /home/goossenm/.rvm/gems/ruby-2.2.2/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
    /home/goossenm/.rvm/gems/ruby-2.2.2/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in`call'
    /home/goossenm/.rvm/gems/ruby-2.2.2/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
    /home/goossenm/.rvm/gems/ruby-2.2.2/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in`call'
    /home/goossenm/.rvm/gems/ruby-2.2.2/gems/rack-1.5.5/lib/rack/logger.rb:15:in `call'
    /home/goossenm/.rvm/gems/ruby-2.2.2/gems/rack-1.5.5/lib/rack/commonlogger.rb:33:in`call'
    /home/goossenm/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:219:in `call'
    /home/goossenm/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:212:in`call'
    /home/goossenm/.rvm/gems/ruby-2.2.2/gems/rack-1.5.5/lib/rack/head.rb:11:in `call'
    /home/goossenm/.rvm/gems/ruby-2.2.2/gems/rack-1.5.5/lib/rack/methodoverride.rb:21:in`call'
    /home/goossenm/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.7/lib/sinatra/show_exceptions.rb:25:in `call'
    /home/goossenm/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:182:in`call'
    /home/goossenm/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:2013:in `call'
    /home/goossenm/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:1487:in`block in call'
    /home/goossenm/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:1787:in `synchronize'
    /home/goossenm/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:1487:in`call'
    /home/goossenm/.rvm/gems/ruby-2.2.2/gems/thin-1.6.4/lib/thin/connection.rb:86:in `block in pre_process'
    /home/goossenm/.rvm/gems/ruby-2.2.2/gems/thin-1.6.4/lib/thin/connection.rb:84:in`catch'
    /home/goossenm/.rvm/gems/ruby-2.2.2/gems/thin-1.6.4/lib/thin/connection.rb:84:in `pre_process'
    /home/goossenm/.rvm/gems/ruby-2.2.2/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:1076:in`call'
    /home/goossenm/.rvm/gems/ruby-2.2.2/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:1076:in `block in spawn_threadpool'`

**Comment by iCHAIT** [comment]
This is because the token expires, I'll commit a change keeping track of the expiration timer obtained from rimesync.

Edit: Fixed

**Comment by MaraJade** [comment]
There needs to be an error check for if there aren't any times for the project. The error I got above is caused by there not being anything to show.

**Comment by iCHAIT** [comment]
I have already placed this check in the backend [here](https://github.com/osuosl/timevis/pull/19/files#diff-cc95738088603531796e0d0f246a5d77R104) but I don't know for some reason it does not get displayed when one such project is selected.

Edit: Fixed

**Comment by iCHAIT** [comment]
@MaraJade fixed both the issues, can you review?

**Comment by Kennric** [comment]
+1

**Pull request merged**
